"""
Talk2Exe Basic - Simple transpile + PyInstaller approach
TE Tribute - Dedicated to TE, creator of PlainTalk

Simple approach:
1. Transpile .talk to Python
2. Use PyInstaller to create .exe
3. Include TE tribute
"""

import sys
import os
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Optional

# TE Tribute constants
TE_TRIBUTE_MESSAGE = "TE Tribute - Dedicated to TE, creator of PlainTalk"
TE_WATERMARK_MESSAGE = "Enhanced by TE"

class Talk2ExeBasic:
    """Basic Talk2Exe converter using PyInstaller"""
    
    def __init__(self):
        self.python_exe = sys.executable
        self.build_log = []
    
    def _log(self, message: str):
        """Add message to build log"""
        timestamp = f"[{len(self.build_log)+1:02d}]"
        log_entry = f"{timestamp} {message}"
        self.build_log.append(log_entry)
        print(log_entry)
    
    def _transpile_talk_to_python(self, talk_file: str) -> str:
        """Transpile PlainTalk to Python"""
        self._log(f"🔄 Transpiling {talk_file}")
        
        try:
            # Import PlainTalk transpiler
            sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
            import plaintalk
            
            # Transpile the file
            with open(talk_file, 'r', encoding='utf-8') as f:
                talk_source = f.read()
            
            python_code = plaintalk.transpile_lines(talk_source.split('\n'))
            
            # Add TE tribute
            te_comment = f"""
# {TE_TRIBUTE_MESSAGE}
# {TE_WATERMARK_MESSAGE}
# Generated by Talk2Exe Basic
"""
            python_code = te_comment + python_code
            
            self._log(f"✅ Transpilation complete with TE tribute")
            return python_code
            
        except Exception as e:
            self._log(f"❌ Transpilation failed: {e}")
            raise RuntimeError(f"Failed to transpile {talk_file}: {e}")
    
    def _create_python_script(self, python_code: str, output_dir: str) -> str:
        """Create the Python script file"""
        script_path = os.path.join(output_dir, "main.py")
        
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(python_code)
        
        self._log(f"✅ Created Python script: {script_path}")
        return script_path
    
    def _create_exe_with_pyinstaller(self, python_script: str, output_exe: str) -> bool:
        """Create executable using PyInstaller"""
        self._log(f"🔧 Creating executable with PyInstaller...")
        
        try:
            output_dir = Path(output_exe).parent
            output_name = Path(output_exe).stem
            
            # PyInstaller command
            cmd = [
                self.python_exe, "-m", "PyInstaller",
                "--onefile",
                "--name", output_name,
                "--distpath", str(output_dir),
                "--workpath", str(output_dir / "build"),
                "--specpath", str(output_dir),
                python_script
            ]
            
            self._log(f"🚀 Running: {' '.join(cmd)}")
            
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            
            if result.returncode == 0:
                self._log(f"✅ PyInstaller completed successfully")
                return True
            else:
                self._log(f"❌ PyInstaller failed: {result.stderr}")
                return False
                
        except subprocess.TimeoutExpired:
            self._log(f"❌ PyInstaller timed out")
            return False
        except Exception as e:
            self._log(f"❌ PyInstaller error: {e}")
            return False
    
    def convert_to_exe(self, input_path: str, output_path: str) -> bool:
        """Main conversion method"""
        try:
            self._log(f"🚀 Starting basic conversion")
            self._log(f"📁 Input: {input_path}")
            self._log(f"📁 Output: {output_path}")
            
            # Validate input
            if not Path(input_path).exists():
                self._log(f"❌ Input file not found: {input_path}")
                return False
            
            if not input_path.endswith('.talk'):
                self._log(f"❌ Input file must have .talk extension")
                return False
            
            # Create output directory
            output_dir = Path(output_path).parent
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Step 1: Transpile .talk to Python
            python_code = self._transpile_talk_to_python(input_path)
            
            # Step 2: Create temporary directory
            temp_dir = tempfile.mkdtemp(prefix="talk2exe_basic_")
            self._log(f"📁 Created temp directory: {temp_dir}")
            
            try:
                # Step 3: Create Python script
                python_script = self._create_python_script(python_code, temp_dir)
                
                # Step 4: Create executable with PyInstaller
                success = self._create_exe_with_pyinstaller(python_script, output_path)
                
                if success:
                    self._log(f"✅ Build completed successfully!")
                    self._log(f"📁 Executable created: {output_path}")
                    self._log(f"🎯 TE tribute embedded in executable")
                    return True
                else:
                    self._log(f"❌ Build failed")
                    return False
                    
            finally:
                # Cleanup
                if os.path.exists(temp_dir):
                    shutil.rmtree(temp_dir)
                    self._log(f"🧹 Cleaned up temp directory: {temp_dir}")
                    
        except Exception as e:
            self._log(f"❌ Conversion failed: {e}")
            return False

def main():
    """Main entry point"""
    if len(sys.argv) != 3:
        print("Talk2Exe Basic - Simple transpile + PyInstaller")
        print(f"{TE_TRIBUTE_MESSAGE}")
        print(f"{TE_WATERMARK_MESSAGE}")
        print("Usage: python Talk2Exe_Basic.py input.talk output.exe")
        print("\nFeatures:")
        print("  • Simple transpile to Python")
        print("  • PyInstaller for .exe creation")
        print("  • TE tribute embedded")
        print("  • No complex security features")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    converter = Talk2ExeBasic()
    success = converter.convert_to_exe(input_file, output_file)
    
    if success:
        print(f"\n🎉 Conversion completed successfully!")
        print(f"Run: {output_file}")
        sys.exit(0)
    else:
        print(f"\n❌ Conversion failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()
