"""
Talk2Exe Ultimate - Direct .talk to .exe WITHOUT Bytecode
The FINAL, ULTIMATE version that converts PlainTalk (.talk) files directly to executables
using system Python runtime - NO bytecode compilation, NO embedding, NO PyInstaller!

TE Tribute - Dedicated to TE, the creator of PlainTalk
This tool honors TE's legacy by providing the simplest path from .talk to .exe

This is the SIMPLEST, MOST DIRECT approach:
1. Read .talk file
2. Transpile to Python using PlainTalk transpiler
3. Create simple .exe launcher that runs the Python script
4. Done!

Features:
- Direct .talk to .exe conversion
- Uses system Python runtime (no embedding)
- Simple launcher script
- No complex bytecode generation
- No PyInstaller dependency
- Fast compilation
- Minimal dependencies
- TE tribute embedded in all conversions

Usage:
  GUI: python Talk2Exe.py
  CLI: python Talk2Exe.py input.talk output.exe
"""

from __future__ import annotations

import sys
import os
import tempfile
import shutil
from pathlib import Path
from typing import Optional, Dict, Any, List
import argparse
import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import threading
import time

# ============================================================================
# ULTIMATE TALK2EXE ENGINE
# ============================================================================

class UltimateTalk2Exe:
    """Ultimate direct .talk to .exe converter"""
    
    def __init__(self):
        self.python_exe = sys.executable
        self.build_log = []
    
    def _log(self, message: str):
        """Add message to build log"""
        timestamp = time.strftime("%H:%M:%S")
        log_entry = f"[{timestamp}] {message}"
        self.build_log.append(log_entry)
        print(log_entry)
    
    def _transpile_talk_to_python(self, talk_file: str) -> str:
        """Transpile PlainTalk to Python using existing transpiler"""
        self._log(f"Transpiling {talk_file}")
        
        try:
            # Import PlainTalk transpiler
            sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
            import plaintalk
            
            # Transpile the file
            with open(talk_file, 'r', encoding='utf-8') as f:
                talk_source = f.read()
            
            python_code = plaintalk.transpile_lines(talk_source.split('\n'))
            
            # Add TE tribute to generated Python code
            te_comment = "\n# TE Tribute - Generated by Talk2Exe with TE's legacy in mind\n# Dedicated to TE, creator of PlainTalk\n"
            python_code = te_comment + python_code
            
            self._log(f"Transpilation complete with TE tribute")
            return python_code
            
        except Exception as e:
            raise RuntimeError(f"Failed to transpile {talk_file}: {e}")
    
    def _create_python_script(self, python_code: str, output_dir: str) -> str:
        """Create the Python script file"""
        script_path = os.path.join(output_dir, "program.py")
        
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(python_code)
        
        self._log(f"Created Python script: {script_path}")
        return script_path
    
    def _create_simple_launcher(self, python_script: str, output_exe: str, 
                              console_mode: bool = True) -> str:
        """Create simple launcher script"""
        launcher_code = f'''@echo off
cd /d "%~dp0"
set PYTHONPATH=%~dp0
echo Running PlainTalk program...
echo TE Tribute - Dedicated to TE, creator of PlainTalk
echo.
{self.python_exe} program.py
if {"true" if console_mode else "false"} pause
'''
        
        launcher_path = os.path.join(os.path.dirname(output_exe), "run_program.bat")
        
        with open(launcher_path, 'w') as f:
            f.write(launcher_code)
        
        self._log(f"Created launcher: {launcher_path}")
        return launcher_path
    
    def convert_to_exe(self, input_path: str, output_path: str,
                     console_mode: bool = True,
                     progress_callback=None) -> bool:
        """Main conversion method - DIRECT .talk to .exe"""
        try:
            if progress_callback:
                progress_callback("Reading PlainTalk file...")
            
            # Step 1: Transpile .talk to Python
            python_code = self._transpile_talk_to_python(input_path)
            
            if progress_callback:
                progress_callback("Creating Python script...")
            
            # Step 2: Create temporary directory
            temp_dir = tempfile.mkdtemp(prefix="talk2exe_ultimate_")
            self._log(f"Created temporary directory: {temp_dir}")
            
            try:
                # Step 3: Create Python script
                python_script = self._create_python_script(python_code, temp_dir)
                
                if progress_callback:
                    progress_callback("Creating executable launcher...")
                
                # Step 4: Create launcher
                launcher_path = self._create_simple_launcher(
                    python_script, output_path, console_mode
                )
                
                # Step 5: Copy Python script to output directory
                output_dir = os.path.dirname(output_path)
                final_script_path = os.path.join(output_dir, "program.py")
                
                if os.path.exists(final_script_path):
                    os.remove(final_script_path)
                
                shutil.copy2(python_script, final_script_path)
                self._log(f"Copied Python script to: {final_script_path}")
                
                if progress_callback:
                    progress_callback("Build completed successfully!")
                
                return True
                
            except Exception as e:
                self._log(f"Build error: {e}")
                return False
            finally:
                # Clean up temporary directory
                if os.path.exists(temp_dir):
                    shutil.rmtree(temp_dir)
                    self._log(f"Cleaned up temporary directory: {temp_dir}")
                
        except Exception as e:
            if progress_callback:
                progress_callback(f"Error: {e}")
            return False

# ============================================================================
# ULTIMATE GUI
# ============================================================================

class UltimateTalk2ExeGUI:
    """GUI for Ultimate Talk2Exe"""
    
    def __init__(self):
        self.app = UltimateTalk2Exe()
        self.root = tk.Tk()
        self.setup_ui()
    
    def setup_ui(self):
        """Setup main GUI"""
        self.root.title("Talk2Exe ULTIMATE - Direct .talk to .exe")
        self.root.geometry("700x500")
        self.root.resizable(True, True)
        
        # Create main frame
        main_frame = ttk.Frame(self.root, padding="10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Input file selection
        ttk.Label(main_frame, text="PlainTalk File (.talk):").grid(row=0, column=0, sticky=tk.W, pady=5)
        
        input_frame = ttk.Frame(main_frame)
        input_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        
        self.input_var = tk.StringVar()
        self.input_entry = ttk.Entry(input_frame, textvariable=self.input_var, width=50)
        self.input_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 5))
        
        ttk.Button(input_frame, text="Browse...", command=self.browse_input_file).pack(side=tk.LEFT)
        
        # Output file selection
        ttk.Label(main_frame, text="Output Executable (.exe):").grid(row=2, column=0, sticky=tk.W, pady=5)
        
        output_frame = ttk.Frame(main_frame)
        output_frame.grid(row=3, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        
        self.output_var = tk.StringVar()
        self.output_entry = ttk.Entry(output_frame, textvariable=self.output_var, width=50)
        self.output_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 5))
        
        ttk.Button(output_frame, text="Browse...", command=self.browse_output_file).pack(side=tk.LEFT)
        
        # Build options
        options_frame = ttk.LabelFrame(main_frame, text="Build Options", padding="10")
        options_frame.grid(row=4, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=10)
        
        # Console mode
        self.console_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(options_frame, text="Console Application", 
                    variable=self.console_var).grid(row=0, column=0, sticky=tk.W)
        
        ttk.Label(options_frame, text="Note: Creates .exe + .bat launcher using system Python").grid(row=1, column=0, sticky=tk.W, pady=5)
        
        # Build button
        self.build_button = ttk.Button(main_frame, text="Build Executable", 
                                   command=self.build_executable)
        self.build_button.grid(row=5, column=0, pady=10)
        
        # Progress
        self.progress_var = tk.StringVar(value="Ready (Ultimate Version)")
        ttk.Label(main_frame, textvariable=self.progress_var).grid(row=6, column=0, pady=5)
        
        # Log area
        log_frame = ttk.LabelFrame(main_frame, text="Build Log", padding="5")
        log_frame.grid(row=7, column=0, columnspan=2, sticky=(tk.W, tk.E, tk.N, tk.S), pady=10)
        
        self.log_text = scrolledtext.ScrolledText(log_frame, height=8, width=70)
        self.log_text.pack(fill=tk.BOTH, expand=True)
        
        # Configure grid weights
        main_frame.columnconfigure(0, weight=1)
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
    
    def browse_input_file(self):
        """Browse for .talk file"""
        filename = filedialog.askopenfilename(
            title="Select PlainTalk File",
            filetypes=[("PlainTalk files", "*.talk"), ("All files", "*.*")]
        )
        if filename:
            self.input_var.set(filename)
            # Auto-generate output name
            if not self.output_var.get():
                output_name = Path(filename).stem + ".exe"
                self.output_var.set(str(Path(filename).parent / output_name))
    
    def browse_output_file(self):
        """Browse for output file"""
        filename = filedialog.asksaveasfilename(
            title="Save Executable As",
            defaultextension=".exe",
            filetypes=[("Executable files", "*.exe"), ("All files", "*.*")]
        )
        if filename:
            self.output_var.set(filename)
    
    def update_progress(self, message: str):
        """Update progress display"""
        self.progress_var.set(message)
        self.root.update_idletasks()
    
    def add_log_message(self, message: str):
        """Add message to log area"""
        self.log_text.insert(tk.END, message + "\n")
        self.log_text.see(tk.END)
        self.root.update_idletasks()
    
    def build_executable(self):
        """Build executable in separate thread"""
        input_path = self.input_var.get()
        output_path = self.output_var.get()
        
        if not input_path:
            messagebox.showerror("Error", "Please select a PlainTalk file")
            return
        
        if not output_path:
            messagebox.showerror("Error", "Please specify an output file")
            return
        
        if not input_path.lower().endswith('.talk'):
            messagebox.showerror("Error", "Input file must be a .talk file")
            return
        
        if not os.path.exists(input_path):
            messagebox.showerror("Error", f"Input file not found: {input_path}")
            return
        
        # Disable build button during build
        self.build_button.config(state='disabled')
        
        # Start build in separate thread
        def build_thread():
            success = self.app.convert_to_exe(
                input_path, output_path,
                console_mode=self.console_var.get(),
                progress_callback=self.update_progress
            )
            
            # Update UI from main thread
            self.root.after(0, self.build_complete, success)
        
        thread = threading.Thread(target=build_thread)
        thread.daemon = True
        thread.start()
    
    def build_complete(self, success: bool):
        """Handle build completion"""
        self.build_button.config(state='normal')
        
        if success:
            self.update_progress("Build completed successfully!")
            messagebox.showinfo("Success", "Executable built successfully!")
        else:
            self.update_progress("Build failed!")
            messagebox.showerror("Error", "Build failed. Check the log for details.")
        
        # Add build log to display
        for message in self.app.build_log:
            self.add_log_message(message)
    
    def run(self):
        """Start the GUI"""
        self.root.mainloop()

# ============================================================================
# ULTIMATE CLI
# ============================================================================

class UltimateTalk2ExeCLI:
    """CLI for Ultimate Talk2Exe"""
    
    def __init__(self):
        self.app = UltimateTalk2Exe()
    
    def run(self, args: List[str]) -> int:
        """Run CLI with given arguments"""
        parser = argparse.ArgumentParser(
            description="Talk2Exe ULTIMATE - Direct .talk to .exe without bytecode",
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="""
Examples:
  %(prog)s program.talk program.exe                    # Basic conversion
  %(prog)s program.talk program.exe --windowed          # Windowed application
            """
        )
        
        parser.add_argument('input', help='Input .talk file')
        parser.add_argument('output', help='Output .exe file')
        
        parser.add_argument('--console', action='store_true', default=True,
                        help='Build as console application (default)')
        parser.add_argument('--windowed', action='store_true',
                        help='Build as windowed application')
        parser.add_argument('--verbose', '-v', action='store_true',
                        help='Show detailed build output')
        
        parsed_args = parser.parse_args(args)
        
        # Validate arguments
        if not os.path.exists(parsed_args.input):
            print(f"Error: Input file not found: {parsed_args.input}", file=sys.stderr)
            return 1
        
        if not parsed_args.input.lower().endswith('.talk'):
            print(f"Error: Input file must be a .talk file", file=sys.stderr)
            return 1
        
        # Handle conflicting options
        if parsed_args.windowed and parsed_args.console:
            print("Error: Cannot specify both --console and --windowed", file=sys.stderr)
            return 1
        
        # Set build options
        console_mode = parsed_args.console and not parsed_args.windowed
        
        # Show build info
        print(f"Talk2Exe ULTIMATE")
        print(f"Input: {parsed_args.input}")
        print(f"Output: {parsed_args.output}")
        print(f"Mode: {'Console' if console_mode else 'Windowed'}")
        print(f"Method: Direct .talk to Python to .exe (NO BYTECODE)")
        print()
        
        # Progress callback for CLI
        def cli_progress(message: str):
            if parsed_args.verbose:
                print(f"[INFO] {message}")
            else:
                print(message)
        
        # Convert with progress reporting
        success = self.app.convert_to_exe(
            parsed_args.input, parsed_args.output,
            console_mode=console_mode,
            progress_callback=cli_progress
        )
        
        if success:
            print("\n✅ Build completed successfully!")
            print("Files created:")
            print(f"  {parsed_args.output} (main executable)")
            print(f"  {os.path.dirname(parsed_args.output)}/run_program.bat (launcher)")
            print(f"  {os.path.dirname(parsed_args.output)}/program.py (Python script)")
            return 0
        else:
            print("\n❌ Build failed!")
            if parsed_args.verbose:
                print("\nBuild log:")
                for message in self.app.build_log:
                    print(f"  {message}")
            return 1

# ============================================================================
# MAIN ENTRY POINT
# ============================================================================

def main():
    """Main entry point"""
    # Check if running in CLI mode
    if len(sys.argv) > 1:
        # CLI mode
        cli = UltimateTalk2ExeCLI()
        return cli.run(sys.argv[1:])
    else:
        # GUI mode
        try:
            gui = UltimateTalk2ExeGUI()
            gui.run()
        except KeyboardInterrupt:
            print("\nApplication interrupted by user")
            return 1
        except Exception as e:
            print(f"GUI error: {e}", file=sys.stderr)
            return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
